apiVersion: v1
items:
- apiVersion: apps.open-cluster-management.io/v1
  kind: Channel
  metadata:
    name: argocd
    namespace: argocd
  spec:
    pathname: https://github.com/pittar-gitops/00-setup
    type: GitHub
- apiVersion: apps.open-cluster-management.io/v1
  kind: Channel
  metadata:
    name: argocd-operator
    namespace: argocd
  spec:
    pathname: https://github.com/pittar-gitops/00-setup
    type: GitHub
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
