apiVersion: v1
items:
- apiVersion: apps.open-cluster-management.io/v1
  kind: Subscription
  metadata:
    name: argocd
    namespace: argocd
  spec:
    channel: argocd
    placement:
      placementRef:
        kind: PlacementRule
        name: argocd
  timeWindow:
    location: America/Toronto
    type: active
- apiVersion: apps.open-cluster-management.io/v1
  kind: Subscription
  metadata:
    annotations:
      apps.open-cluster-management.io/github-branch: master
      apps.open-cluster-management.io/github-path: /argocd/overlays/default
    labels:
      app: argocd-app
    name: argocd-app
    namespace: argocd
  spec:
    channel: argocd/argocd
    placement:
      placementRef:
        kind: PlacementRule
        name: gitops-argocd
- apiVersion: apps.open-cluster-management.io/v1
  kind: Subscription
  metadata:
    annotations:
      apps.open-cluster-management.io/github-branch: master
      apps.open-cluster-management.io/github-path: /argocd-operator/overlays/default
    labels:
      app: argocd-operator
    name: argocd-operator
    namespace: argocd
  spec:
    channel: argocd/argocd-operator
    placement:
      placementRef:
        kind: PlacementRule
        name: gitops-argocd
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
